### ISSUE TITLE
Error with keyble, then die 

### ISSUE THREAD

**Issue by nerdosity** [oyooyo/simble#2]
Hello, I followed your guide for using keyble.
It almost work, but it hangs too often when used as a service. That's a shame, since it is more usable as a service from home assistant:

root@raspberrypi:~/.homeassistant# /usr/local/bin/smartlock.sh
Error: Promise did not resolve within 45000 milliseconds
Error: Promise did not resolve within 45000 milliseconds
(node:30985) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'connect' of null
    at Promise (/usr/lib/node_modules/keyble/node_modules/simble/simble.js:549:33)
    at new Promise (<anonymous>)
    at _Class.ensure_connected (/usr/lib/node_modules/keyble/node_modules/simble/simble.js:544:14)
    at _Class.ensure_discovered (/usr/lib/node_modules/keyble/node_modules/simble/simble.js:582:19)
    at ensure_peripheral.then (/usr/lib/node_modules/keyble/keyble.js:888:85)
    at <anonymous>
(node:30985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled w    ith .catch(). (rejection id: 3)
(node:30985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: TypeError: Cannot read property 'connect' of null
Error: TypeError: Cannot read property 'connect' of null
Error: TypeError: Cannot read property 'connect' of null
Error: TypeError: Cannot read property 'connect' of null
Error: TypeError: Cannot read property 'connect' of null
Error: TypeError: Cannot read property 'connect' of null

**Comment by andrexp** [comment]
I had also trouble with this.
I.m.h.o. the error does not seem to be issued by simble. I am also not very familiar with nodejs but I have a workaround that works for me. For everyone who wants a quick and dirty solution add the following to line 860 of keyble.js:

`if (this.peripheral)
{
  if(this.peripheral.state > 1) 
  {
    return Promise.resolve(this.peripheral);
  } 
}`

This will create a new connection object everytime the current state is lower 1 (disconnected)

Hope it helps...
